### ISSUE TITLE
Bigwigs voice throwing lua error

### ISSUE THREAD

**Issue by klepp0906** [BigWigsMods/BigWigs_Voice#4]
1x BigWigs_Voice\Core.lua:19: script ran too long
BigWigs_Voice\Core.lua:19: in function `v'
BigWigs\Loader.lua:631: in function `SendMessage'
BigWigs_Core\BossPrototype.lua:1347: in function `Message'
BigWigs_Nightmare\Xavius.lua:372: in function `?'
BigWigs_Core\BossPrototype.lua:391: in function <BigWigs_Core\BossPrototype.lua:358>

Locals:

**Comment by funkydude** [comment]
Nothing we can do. Probably a slow machine, a random lag spike, etc. Taking too long to play a sound file is not fixable.

**Comment by klepp0906** [comment]
def not a slow pc, 4.8ghz devils canyon w/ dual 1080's and 32gb of ram on a ssd raid 0 array..

hasnt worked outside of the 5/4/3/2/1 since i installed it.  guess ill tinker w/ it s'more and hope for the best.

thanks!

**Comment by funkydude** [comment]
Could also be a bad sound card, old sound drivers, etc.

The countdown is unrelated to this addon, this addon is all about TTS.

**Comment by klepp0906** [comment]
I appreciate your replies, i know its probably frustrating, annoying, and difficult trying to help everyone.

With that being said, i have nowhere else to turn and am really hoping to avoid moving over to dbm.  I use an integrated sound card like most these days (7.1 HD) and just updated to the newest drivers (mine were a version or two back).

Also reinstalled bigwigs voice.  The same error appeared in bugsack.  Any addons you can think of it conflicting with?  I use ELVUI is that an issue?

**Comment by funkydude** [comment]
If you want to test if it may be a conflict you are free to do so. All you need to do is disable all your non-BW addons and jump into an LFR. I'm afraid I cannot help you much, so anything you want to try I'd say go for it. You can also try deleting your BW related saved variables.

I do however find it highly odd that this issue seems to happen 100% for you. Taking too long to play a sound file has always been a random occurrence for people, usually due to a lag spike of some form. The only time I've heard of people stating it was 100% was when they were playing on dated laptops.
